[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "invEngine"
version = "0.1.0"
<<<<<<< HEAD
description = "A python compiler module for a mini language that allows you to create Minecraft mini games within the player's inventory with a SINGLE command"
authors = [{ name = "Norcith" }]
=======
description = "Inventory engine"
authors = [{ name = "David Pavie" }]
>>>>>>> 74e964300453f5eb8a8d45099e9bd5072567f529
requires-python = ">=3.10"